create extension if not exists pg_cron;
create extension if not exists pg_net;

create table if not exists public.market_price_updates (
  id bigint generated by default as identity primary key,
  gold18_toman numeric not null,
  gold18_rial numeric not null,
  source text not null,
  source_url text not null,
  fetched_at timestamptz not null default now(),
  status text not null default 'success',
  error_message text
);

alter table public.market_price_updates enable row level security;

drop policy if exists "no_public_market_price_update_reads" on public.market_price_updates;
create policy "no_public_market_price_update_reads"
on public.market_price_updates
for select
to anon, authenticated
using (false);

create table if not exists public.market_price_fetch_requests (
  request_id bigint primary key,
  requested_at timestamptz not null default now(),
  processed_at timestamptz,
  status text
);

alter table public.market_price_fetch_requests enable row level security;

drop policy if exists "no_public_market_price_fetch_reads" on public.market_price_fetch_requests;
create policy "no_public_market_price_fetch_reads"
on public.market_price_fetch_requests
for select
to anon, authenticated
using (false);

create or replace function public.queue_gold18_price_fetch()
returns bigint
language plpgsql
security definer
set search_path = public, net
as $$
declare
  v_request_id bigint;
begin
  select net.http_get(
    'https://www.tgju.org/profile/geram18'
  ) into v_request_id;

  insert into public.market_price_fetch_requests(request_id)
  values (v_request_id);

  return v_request_id;
end;
$$;

create or replace function public.process_gold18_price_fetch()
returns jsonb
language plpgsql
security definer
set search_path = public, net
as $$
declare
  v_request public.market_price_fetch_requests%rowtype;
  v_response record;
  v_price_text text;
  v_rial numeric;
  v_toman numeric;
  v_current numeric;
  v_change_ratio numeric;
begin
  select *
  into v_request
  from public.market_price_fetch_requests
  where processed_at is null
  order by requested_at asc
  limit 1
  for update skip locked;

  if not found then
    return jsonb_build_object('status','nothing_to_process');
  end if;

  select *
  into v_response
  from net._http_response
  where id = v_request.request_id
  limit 1;

  if not found or coalesce(v_response.status_code, 0) <> 200 or v_response.content is null then
    update public.market_price_fetch_requests
    set processed_at = now(), status = 'http_error'
    where request_id = v_request.request_id;

    insert into public.market_price_updates(
      gold18_toman, gold18_rial, source, source_url, fetched_at, status, error_message
    )
    values (
      0, 0, 'TGJU', 'https://www.tgju.org/profile/geram18',
      coalesce(v_response.created, v_request.requested_at),
      'error',
      coalesce(v_response.error_msg, 'TGJU response unavailable')
    );

    return jsonb_build_object('status','http_error');
  end if;

  v_price_text := substring(
    v_response.content
    from 'data-col="info\\.last_trade\\.PDrCotVal">([0-9,]+)'
  );

  if v_price_text is null then
    update public.market_price_fetch_requests
    set processed_at = now(), status = 'parse_error'
    where request_id = v_request.request_id;

    insert into public.market_price_updates(
      gold18_toman, gold18_rial, source, source_url, fetched_at, status, error_message
    )
    values (
      0, 0, 'TGJU', 'https://www.tgju.org/profile/geram18',
      coalesce(v_response.created, v_request.requested_at),
      'error',
      'Price marker not found in TGJU response'
    );

    return jsonb_build_object('status','parse_error');
  end if;

  v_rial := replace(v_price_text, ',', '')::numeric;
  v_toman := v_rial / 10;

  if v_toman < 1000000 or v_toman > 1000000000 then
    update public.market_price_fetch_requests
    set processed_at = now(), status = 'sanity_error'
    where request_id = v_request.request_id;

    insert into public.market_price_updates(
      gold18_toman, gold18_rial, source, source_url, fetched_at, status, error_message
    )
    values (
      v_toman, v_rial, 'TGJU', 'https://www.tgju.org/profile/geram18',
      coalesce(v_response.created, v_request.requested_at),
      'error',
      'Parsed price failed absolute sanity check'
    );

    return jsonb_build_object('status','sanity_error','gold18_toman',v_toman);
  end if;

  select gold18 into v_current
  from public.market_prices
  where id = 1
  for update;

  if v_current is not null and v_current > 0 then
    v_change_ratio := abs(v_toman - v_current) / v_current;
  else
    v_change_ratio := 0;
  end if;

  if v_change_ratio > 0.20 then
    update public.market_price_fetch_requests
    set processed_at = now(), status = 'suspicious'
    where request_id = v_request.request_id;

    insert into public.market_price_updates(
      gold18_toman, gold18_rial, source, source_url, fetched_at, status, error_message
    )
    values (
      v_toman, v_rial, 'TGJU', 'https://www.tgju.org/profile/geram18',
      coalesce(v_response.created, v_request.requested_at),
      'suspicious',
      'Price moved more than 20 percent from previous stored price'
    );

    return jsonb_build_object(
      'status','suspicious',
      'gold18_toman',v_toman,
      'previous_gold18_toman',v_current
    );
  end if;

  update public.market_prices
  set gold18 = v_toman,
      updated_at = coalesce(v_response.created, now())
  where id = 1;

  update public.market_price_fetch_requests
  set processed_at = now(), status = 'success'
  where request_id = v_request.request_id;

  insert into public.market_price_updates(
    gold18_toman, gold18_rial, source, source_url, fetched_at, status
  )
  values (
    v_toman, v_rial, 'TGJU', 'https://www.tgju.org/profile/geram18',
    coalesce(v_response.created, now()),
    'success'
  );

  return jsonb_build_object(
    'status','success',
    'gold18_toman',v_toman,
    'gold18_rial',v_rial,
    'fetched_at',coalesce(v_response.created, now())
  );
end;
$$;

revoke execute on function public.queue_gold18_price_fetch() from public, anon, authenticated;
revoke execute on function public.process_gold18_price_fetch() from public, anon, authenticated;

select cron.schedule(
  'talayab-gold18-fetch-hourly',
  '0 * * * *',
  $$select public.queue_gold18_price_fetch();$$
);

select cron.schedule(
  'talayab-gold18-process',
  '*/5 * * * *',
  $$select public.process_gold18_price_fetch();$$
);
